### ISSUE TITLE
Get Video Thumb API for Vimeo is dead

### ISSUE THREAD

**Issue by VincenzoMarsianoBcame** [nk-o/video-worker#21]
Hi, 
I discovered that the API endpoint used by getImageURL() in video-worker.js for Vimeo is dead, they have changed API endpoints so the ones used in the method code is deprecated.

**Comment by nk-o** [comment]
Hey.

Can you provide an example? I just tested it locally and it is working as expected. Without any problem.

**Comment by VincenzoMarsianoBcame** [comment]
Hii, 
thank you for the answer firstly,
i realized that my client want to use private vimeo videos, could this be a problem?
because i tried also another service, "https://vumbnail.com", but some IDs cannot be found, maybe due to privacy about private videos

**Comment by nk-o** [comment]
Yes, we can look at the public videos only (and their thumbnails). I don't think we will add support for private access, as we personally never use it.
